packages:
  - playground/*
  - docs
  - packages/*
  - examples/*

catalogs:
  build:
    '@vitejs/plugin-vue': ^6.0.1
    unocss: ^66.4.2
    unplugin-vue-components: ^28.1.0
    vite-tsconfig-paths: ^5.1.4
    vitepress: ^2.0.0-alpha.11
    vitepress-plugin-group-icons: ^1.3.5
  cli:
    '@antfu/eslint-config': ^5.2.1
    '@antfu/ni': ^25.0.0
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^16.1.5
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    unbuild: ^3.5.0
    vite: ^7.1.3
  frontend:
    '@iconify-json/svg-spinners': ^1.2.2
    '@shikijs/vitepress-twoslash': ^2.3.2
    '@unocss/reset': ^65.5.0
    '@vueuse/core': ^12.7.0
    floating-vue: ^5.2.2
    pinia: ^3.0.1
    vue: ^3.5.18
  inlined:
    '@antfu/utils': ^9.1.0
  prod:
    c12: ^3.2.0
    chokidar: ^5.0.0
    citty: ^0.1.6
    consola: ^3.4.2
    defu: ^6.1.4
    dotenv: ^16.4.7
    dotenv-expand: ^12.0.1
    es-module-lexer: ^1.4.1
    exsolve: ^1.0.7
    fast-glob: ^3.3.2
    hookable: ^5.5.3
    jiti: ^2.5.1
    micromatch: ^4.0.8
    pathe: ^2.0.3
    pkg-types: ^2.3.0
    scule: ^1.3.0
    unctx: ^2.4.1
    untyped: ^2.0.0
  testing:
    vitest: ^3.2.4
  types:
    '@types/micromatch': ^4.0.10
    '@types/node': ^24.3.0
