import type { ResourceManifest } from '@vona-js/schema'

export function generateDTS(manifest: ResourceManifest): string {
  const lines: string[] = [
    '// Auto-generated by Vona',
    '// DO NOT EDIT',
    '',
    'declare module \'vona:*\' {',
    '  export * from \'vona:types\'',
    '}',
    '',
    'declare module \'vona:types\' {',
  ]

  const components = manifest.resources.components
  if (components.length > 0) {
    lines.push('')
    lines.push('  // Components')
    lines.push('  interface Components {')
    for (const asset of components) {
      lines.push(`    ${asset.name.pascal}: typeof import('${asset.loader.relative}')['default']`)
    }
    lines.push('  }')
  }

  const pages = manifest.resources.pages
  if (pages.length > 0) {
    lines.push('')
    lines.push('  // Pages')
    lines.push('  interface Pages {')
    for (const asset of pages) {
      lines.push(`    '${asset.route?.path ?? '/'}': typeof import('${asset.loader.relative}')['default']`)
    }
    lines.push('  }')
  }

  const layouts = manifest.resources.layouts
  if (layouts.length > 0) {
    lines.push('')
    lines.push('  // Layouts')
    lines.push('  interface Layouts {')
    for (const asset of layouts) {
      lines.push(`    ${asset.name.pascal}: typeof import('${asset.loader.relative}')['default']`)
    }
    lines.push('  }')
  }

  const composables = manifest.resources.composables
  if (composables.length > 0) {
    lines.push('')
    lines.push('  // Composables')
    for (const asset of composables) {
      if (asset.loader.importName) {
        lines.push(`  const ${asset.loader.importName}: typeof import('${asset.loader.relative}')['${asset.loader.importName}']`)
      }
    }
  }

  const apis = manifest.resources.apis
  if (apis.length > 0) {
    lines.push('')
    lines.push('  // APIs')
    for (const asset of apis) {
      if (asset.loader.importName) {
        lines.push(`  const ${asset.loader.importName}: typeof import('${asset.loader.relative}')['${asset.loader.importName}']`)
      }
    }
  }

  lines.push('')
  lines.push('  export {')
  lines.push('    Components,')
  lines.push('    Pages,')
  lines.push('    Layouts,')
  lines.push('  }')
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}
